version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gosample_test
      POSTGRES_USER: circleci
      POSTGRES_PASSWORD: circleci
  circleci:
    depends_on:
      - db
    image: synqfm/circleci:0.1.5
    #  ports:
    #    - "8000:80"
    restart: always
    #  environment:
    #    WORDPRESS_DB_HOST: db:3306
    #    WORDPRESS_DB_USER: wordpress
    #    WORDPRESS_DB_PASSWORD: wordpress
  pgadmin:
    depends_on:
      - db
    image: fenglc/pgadmin4:latest
    ports:
      - "5050:5050"
    restart: always
    #  environment:
    #    WORDPRESS_DB_HOST: db:3306
    #    WORDPRESS_DB_USER: wordpress
    #    WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
